name: Scheduled Health Check

# Controls when the action will run.
on:
  schedule:
    - cron: "30 * * * *"
  workflow_dispatch:

jobs:
  health_check_job:
    runs-on: ubuntu-latest
    name: Check all sites
    steps:
      - uses: actions/checkout@v2
      - name: Run Shell Script
        id: shell_script_run
        run: bash ./health-check.sh
      - name: Check for failed systems and trigger email notifications
        id: check_failed
        run: |
          bash ./notify_failed_systems.sh
          if [[ -f logs/email_triggers.txt ]]; then
            echo "failed_systems<<EOF" >> $GITHUB_OUTPUT
            cat logs/email_triggers.txt >> $GITHUB_OUTPUT
            echo "EOF" >> $GITHUB_OUTPUT
          fi
      - name: Log failed systems to output
        if: success() && hashFiles('logs/email_triggers.txt') != ''
        run: |
         echo "The following systems have failed and require attention:"
         echo "${{ steps.check_failed.outputs.failed_systems }}"
      - name: Update failed_systems.log after notifications
        if: success() && hashFiles('logs/email_triggers.txt') != ''
        run: bash ./update_failed_systems_log.sh
      - name: Commit and Push Logs
        run: |
          git config --global user.name 'Tom Pool'
          git config --global user.email 'tom.pool@york.ac.uk.com'
          git add -A --force logs/
          git commit -am '[Automated] Update Health Check Logs'
          git push
