name: Scheduled Health Check

# Controls when the action will run.
on:
  schedule:
    - cron: "30 * * * *"
  workflow_dispatch:

jobs:
  health_check_job:
    runs-on: ubuntu-latest
    name: Check all sites
    steps:
      - uses: actions/checkout@v2
      - name: Run Shell Script
        id: shell_script_run
        run: bash ./health-check.sh
      - name: Check for failed systems and trigger email notifications
        run: bash ./notify_failed_systems.sh
      - name: Log failed systems to output
        if: success() && hashFiles('logs/email_triggers.txt') != ''
        run: |
         echo "The following systems have failed and require attention:"
         echo "${{ steps.shell_script_run.outputs.failed_keys }}"
      - name: Update failed_systems.log after notifications
        if: success() && hashFiles('logs/email_triggers.txt') != ''
        run: bash ./update_failed_systems_log.sh
